/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Domain.Person;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author 主子
 */
public class PersonView extends javax.swing.JPanel {

    /**
     * Creates new form PersonView
     */
    Person person;
    public PersonView(Person person) {
        initComponents();
        this.person=person;

        try{
            this.fieldFirstName3.setText(person.getFirstName());
            this.fieldLastName.setText(person.getLastName());
            this.fieldBirthday.setText(person.getDateOfBirth());
            this.fieldSSN.setText(person.getSSN());
            this.fieldHeight.setText(person.getHeight());
            this.fieldWeight.setText(person.getWeight());
            this.fieldStreetAddress.setText(person.getStreetAddressArea());
        // workAddress
            this.addressStreetLine1.setText(person.getWorkAdress().getAdressLine1());
            this.addressStreetLine2.setText(person.getWorkAdress().getAdressLine2());
            this.addressCity.setText(person.getWorkAdress().getCity());
            this.addressCountry.setText(person.getWorkAdress().getCountry());
            this.addressState.setText(person.getWorkAdress().getState());
            this.addressZipCode.setText(person.getWorkAdress().getZipCode());
        
//            Local Address
            this.localAddressSL1.setText(person.getLocalAdress().getAdressLine1());
            this.localAddressSL2.setText(person.getLocalAdress().getAdressLine2());
            this.localAddressCountry.setText(person.getLocalAdress().getCountry());
            this.localAddressState.setText(person.getLocalAdress().getState());
            this.localAddressCity.setText(person.getLocalAdress().getCity());
            this.localAddressZC3.setText(person.getLocalAdress().getZipCode());
        
        //Home Address
        this.homeAddressSL1.setText(person.getHomeAdress().getAdressLine1());
        this.homeAddressL2.setText(person.getHomeAdress().getAdressLine2());
        this.homeAddressCountry.setText(person.getHomeAdress().getCountry());
        this.homeAddressState.setText(person.getHomeAdress().getState());
        this.homeAddressCity.setText(person.getHomeAdress().getCity());
        this.homeAddressZipcode.setText(person.getHomeAdress().getZipCode());
        
        //Saving Account
        this.fieldBankName.setText(person.getSavingAccount().getBankName());
        this.fieldBRN.setText(person.getSavingAccount().getBankRoutingNumber());
        this.fieldBAN.setText(person.getSavingAccount().getBankAccountNumber());
        this.fieldAccountType.setText(person.getSavingAccount().getAccountType());
            if (person.getSavingAccount().getAccountBalance() == 0) {
                this.fieldAccountBalance.setText("" + 0);
            } else {
                this.fieldAccountBalance.setText(""+person.getSavingAccount().getAccountBalance());
            }
        
        
        //Checking Account
        this.fieldBankName1.setText(person.getCheckingAccount().getBankName());
        this.fieldBRN1.setText(person.getCheckingAccount().getBankRoutingNumber());
        this.fieldBAN1.setText(person.getCheckingAccount().getBankAccountNumber());
        this.fieldAccountType1.setText(person.getCheckingAccount().getAccountType());
        if(person.getCheckingAccount().getAccountBalance()==0){
            this.fieldAccountBalance1.setText(""+0);
        }else{
            this.fieldAccountBalance1.setText(""+person.getCheckingAccount().getAccountBalance());
        }
        
        
        //Driver's Licence
        this.fieldLicenceNumber.setText(person.getDriverLicence().getLicenceNumber());
        this.fieldBloodType.setText(person.getDriverLicence().getBloodType());
        this.fieldDOE.setText(person.getDriverLicence().getDateOfExpiration());
        this.fieldDateIssued.setText(person.getDriverLicence().getDateIssued());

        ImageIcon imagThisImag=person.getDriverLicence().getImgPortrait();
        this.photoLicence.setIcon(imagThisImag);
            
        //Medical Record
        this.fieldMRNAlergy1.setText(person.getMedicalRecord().getMedicalRecordNumber());
        this.fieldMRNAlergy2.setText(person.getMedicalRecord().getMedicalRecordNumber());
        this.fieldMRNAlergy3.setText(person.getMedicalRecord().getMedicalRecordNumber());
        
        }catch(Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        fieldFirstName3 = new javax.swing.JTextField();
        fieldWeight = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        tab4 = new javax.swing.JTabbedPane();
        tabAddress3 = new javax.swing.JPanel();
        localAddressZC3 = new javax.swing.JTextField();
        localAddressCountry = new javax.swing.JTextField();
        homeAddressState = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        homeAddressSL1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        homeAddressL2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        homeAddressCity = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        homeAddressZipcode = new javax.swing.JTextField();
        homeAddressCountry = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        addressStreetLine1 = new javax.swing.JTextField();
        addressStreetLine2 = new javax.swing.JTextField();
        addressCity = new javax.swing.JTextField();
        addressState = new javax.swing.JTextField();
        addressZipCode = new javax.swing.JTextField();
        addressCountry = new javax.swing.JTextField();
        localAddressState = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        localAddressSL1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        localAddressSL2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        localAddressCity = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tabAccount = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        fieldBankName = new javax.swing.JTextField();
        fieldBRN = new javax.swing.JTextField();
        fieldBAN = new javax.swing.JTextField();
        fieldAccountBalance = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        fieldBRN1 = new javax.swing.JTextField();
        fieldBAN1 = new javax.swing.JTextField();
        fieldAccountBalance1 = new javax.swing.JTextField();
        fieldAccountType1 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        fieldBankName1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabLicence = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        fieldLicenceNumber = new javax.swing.JTextField();
        fieldDOE = new javax.swing.JTextField();
        fieldBloodType = new javax.swing.JTextField();
        fieldDateIssued = new javax.swing.JTextField();
        photoLicence = new javax.swing.JLabel();
        tabMedical = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        fieldMRNAlergy1 = new javax.swing.JTextField();
        fieldMRNAlergy2 = new javax.swing.JTextField();
        fieldMRNAlergy3 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fieldSSN = new javax.swing.JTextField();
        fieldBirthday = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        fieldHeight = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldStreetAddress11 = new javax.swing.JScrollPane();
        fieldStreetAddress = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(62, 188, 202));
        setPreferredSize(new java.awt.Dimension(827, 585));

        jLabel27.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Height");

        fieldFirstName3.setEditable(false);
        fieldFirstName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstName3ActionPerformed(evt);
            }
        });

        fieldWeight.setEditable(false);

        jLabel44.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel44.setText("SSN");

        tab4.setBackground(new java.awt.Color(62, 188, 202));
        tab4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tab4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab4.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        tabAddress3.setBackground(new java.awt.Color(62, 188, 202));
        tabAddress3.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        tabAddress3.setPreferredSize(new java.awt.Dimension(827, 585));

        localAddressZC3.setEditable(false);
        localAddressZC3.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        localAddressZC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localAddressZC3ActionPerformed(evt);
            }
        });

        localAddressCountry.setEditable(false);
        localAddressCountry.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        homeAddressState.setEditable(false);
        homeAddressState.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel21.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel21.setText("Street Line1");

        jLabel22.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel22.setText("Street Line2");

        homeAddressSL1.setEditable(false);
        homeAddressSL1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        homeAddressSL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAddressSL1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel23.setText("City");

        homeAddressL2.setEditable(false);
        homeAddressL2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel24.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel24.setText("State");

        homeAddressCity.setEditable(false);
        homeAddressCity.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        homeAddressCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAddressCityActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel25.setText("Zip code");

        jLabel26.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel26.setText("Country");

        homeAddressZipcode.setEditable(false);
        homeAddressZipcode.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        homeAddressZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAddressZipcodeActionPerformed(evt);
            }
        });

        homeAddressCountry.setEditable(false);
        homeAddressCountry.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel28.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel28.setText("Work Address");

        jLabel29.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel29.setText("Local Address");

        jLabel30.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel30.setText("Home Address");

        jLabel31.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel31.setText("Street Line1");

        jLabel32.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel32.setText("Street Line2");

        jLabel33.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel33.setText("City");

        jLabel34.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel34.setText("State");

        jLabel35.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel35.setText("Zip code");

        jLabel36.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel36.setText("Country");

        addressStreetLine1.setEditable(false);
        addressStreetLine1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        addressStreetLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressStreetLine1ActionPerformed(evt);
            }
        });

        addressStreetLine2.setEditable(false);
        addressStreetLine2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        addressCity.setEditable(false);
        addressCity.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        addressCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressCityActionPerformed(evt);
            }
        });

        addressState.setEditable(false);
        addressState.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        addressZipCode.setEditable(false);
        addressZipCode.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        addressZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressZipCodeActionPerformed(evt);
            }
        });

        addressCountry.setEditable(false);
        addressCountry.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        localAddressState.setEditable(false);
        localAddressState.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel37.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel37.setText("Street Line1");

        jLabel38.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel38.setText("Street Line2");

        localAddressSL1.setEditable(false);
        localAddressSL1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel39.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel39.setText("City");

        localAddressSL2.setEditable(false);
        localAddressSL2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel40.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel40.setText("State");

        localAddressCity.setEditable(false);
        localAddressCity.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        localAddressCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localAddressCityActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel41.setText("Zip code");

        jLabel42.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel42.setText("Country");

        javax.swing.GroupLayout tabAddress3Layout = new javax.swing.GroupLayout(tabAddress3);
        tabAddress3.setLayout(tabAddress3Layout);
        tabAddress3Layout.setHorizontalGroup(
            tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddress3Layout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddress3Layout.createSequentialGroup()
                        .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homeAddressCity)
                            .addComponent(homeAddressZipcode)
                            .addComponent(homeAddressCountry)
                            .addComponent(homeAddressState)
                            .addComponent(homeAddressSL1)
                            .addComponent(homeAddressL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddress3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(69, 69, 69)))
                .addContainerGap())
            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabAddress3Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabAddress3Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(jLabel31)
                                .addComponent(jLabel33)
                                .addComponent(jLabel34)
                                .addComponent(jLabel35)
                                .addComponent(jLabel36))
                            .addGap(3, 3, 3)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressStreetLine2)
                                .addComponent(addressCity)
                                .addComponent(addressZipCode)
                                .addComponent(addressCountry)
                                .addComponent(addressState)
                                .addComponent(addressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tabAddress3Layout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(196, 196, 196)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29)
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel38)
                                        .addComponent(jLabel37)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel40)
                                        .addComponent(jLabel41)
                                        .addComponent(jLabel42))
                                    .addGap(3, 3, 3)
                                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(localAddressSL2)
                                        .addComponent(localAddressSL1)
                                        .addComponent(localAddressZC3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(localAddressCountry)
                                        .addComponent(localAddressState)
                                        .addComponent(localAddressCity))))))
                    .addGap(276, 276, 276)))
        );
        tabAddress3Layout.setVerticalGroup(
            tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddress3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(28, 28, 28)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(homeAddressSL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(homeAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAddress3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel24))
                    .addGroup(tabAddress3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(homeAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(homeAddressZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(homeAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabAddress3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29))
                    .addGap(28, 28, 28)
                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabAddress3Layout.createSequentialGroup()
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(addressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(addressStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33)
                                .addComponent(addressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel34))
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(addressState, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(addressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel36)
                                .addComponent(addressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tabAddress3Layout.createSequentialGroup()
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel37)
                                .addComponent(localAddressSL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel38)
                                .addComponent(localAddressSL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel39)
                                .addComponent(localAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel40))
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(localAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel41)
                                .addComponent(localAddressZC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel42)
                                .addComponent(localAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tab4.addTab("Address", tabAddress3);

        tabAccount.setBackground(new java.awt.Color(62, 188, 202));

        jLabel45.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel45.setText("Bank Name");

        jLabel46.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel46.setText("Bank Routing Number");

        jLabel47.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel47.setText("Bank Account Number");

        jLabel48.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel48.setText("Account Balance");

        jLabel49.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel49.setText("Account Type");

        fieldBankName.setEditable(false);
        fieldBankName.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBRN.setEditable(false);
        fieldBRN.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBAN.setEditable(false);
        fieldBAN.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldAccountBalance.setEditable(false);
        fieldAccountBalance.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldAccountType.setEditable(false);
        fieldAccountType.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBRN1.setEditable(false);
        fieldBRN1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBAN1.setEditable(false);
        fieldBAN1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldAccountBalance1.setEditable(false);
        fieldAccountBalance1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldAccountType1.setEditable(false);
        fieldAccountType1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel61.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel61.setText("Bank Name");

        jLabel62.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel62.setText("Bank Routing Number");

        jLabel63.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel63.setText("Bank Account Number");

        jLabel64.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel64.setText("Account Balance");

        jLabel65.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel65.setText("Account Type");

        fieldBankName1.setEditable(false);
        fieldBankName1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel1.setText("Checking Account");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel2.setText("Saving Account");

        javax.swing.GroupLayout tabAccountLayout = new javax.swing.GroupLayout(tabAccount);
        tabAccount.setLayout(tabAccountLayout);
        tabAccountLayout.setHorizontalGroup(
            tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(tabAccountLayout.createSequentialGroup()
                            .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel48)
                                .addComponent(jLabel49))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldBRN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tabAccountLayout.createSequentialGroup()
                            .addComponent(jLabel45)
                            .addGap(121, 121, 121)
                            .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63)
                    .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(tabAccountLayout.createSequentialGroup()
                            .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel64)
                                .addComponent(jLabel65))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldAccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldAccountBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldBAN1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldBRN1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tabAccountLayout.createSequentialGroup()
                            .addComponent(jLabel61)
                            .addGap(121, 121, 121)
                            .addComponent(fieldBankName1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        tabAccountLayout.setVerticalGroup(
            tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabAccountLayout.createSequentialGroup()
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBankName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBRN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBAN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAccountBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel64))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel65)
                            .addComponent(fieldAccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabAccountLayout.createSequentialGroup()
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBankName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBRN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tab4.addTab("Account", tabAccount);

        tabLicence.setBackground(new java.awt.Color(62, 188, 202));
        tabLicence.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel50.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel50.setText("License Number");

        jLabel51.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel51.setText("Date of Expiration");

        jLabel52.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel52.setText("Blood Type");

        jLabel53.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel53.setText("Date issued");

        jLabel54.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel54.setText("DRIVING LICENSE");

        fieldLicenceNumber.setEditable(false);
        fieldLicenceNumber.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldDOE.setEditable(false);
        fieldDOE.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBloodType.setEditable(false);
        fieldBloodType.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldDateIssued.setEditable(false);
        fieldDateIssued.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        photoLicence.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        photoLicence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLicence.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout tabLicenceLayout = new javax.swing.GroupLayout(tabLicence);
        tabLicence.setLayout(tabLicenceLayout);
        tabLicenceLayout.setHorizontalGroup(
            tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLicenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photoLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabLicenceLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldDateIssued, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldLicenceNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(fieldDOE)))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        tabLicenceLayout.setVerticalGroup(
            tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLicenceLayout.createSequentialGroup()
                .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabLicenceLayout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(fieldLicenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(fieldDOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(fieldBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(fieldDateIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabLicenceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(photoLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tab4.addTab("Driver's License", tabLicence);

        tabMedical.setBackground(new java.awt.Color(62, 188, 202));
        tabMedical.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel55.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel55.setText("Alergy1");

        jLabel56.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel56.setText("Alergy2");

        jLabel57.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel57.setText("Alergy3");

        fieldMRNAlergy1.setEditable(false);
        fieldMRNAlergy1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        fieldMRNAlergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMRNAlergy1ActionPerformed(evt);
            }
        });

        fieldMRNAlergy2.setEditable(false);
        fieldMRNAlergy2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldMRNAlergy3.setEditable(false);
        fieldMRNAlergy3.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel58.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel58.setText("MRN");

        jLabel59.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel59.setText("MRN");

        jLabel60.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel60.setText("MRN");

        javax.swing.GroupLayout tabMedicalLayout = new javax.swing.GroupLayout(tabMedical);
        tabMedical.setLayout(tabMedicalLayout);
        tabMedicalLayout.setHorizontalGroup(
            tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMedicalLayout.createSequentialGroup()
                .addGroup(tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabMedicalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(tabMedicalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldMRNAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabMedicalLayout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                        .addComponent(jLabel57)
                        .addGap(114, 114, 114))
                    .addGroup(tabMedicalLayout.createSequentialGroup()
                        .addComponent(fieldMRNAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldMRNAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        tabMedicalLayout.setVerticalGroup(
            tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMedicalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldMRNAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMRNAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMRNAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        tab4.addTab("Medical Record", tabMedical);

        jLabel18.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel18.setText("Last Name");

        jLabel16.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel16.setText("Person Profile View");

        fieldSSN.setEditable(false);

        fieldBirthday.setEditable(false);

        jLabel19.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel19.setText("Street Address");

        jLabel43.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel43.setText("Weight");

        fieldHeight.setEditable(false);
        fieldHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHeightActionPerformed(evt);
            }
        });

        fieldLastName.setEditable(false);
        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        fieldStreetAddress.setEditable(false);
        fieldStreetAddress.setColumns(20);
        fieldStreetAddress.setLineWrap(true);
        fieldStreetAddress.setRows(5);
        fieldStreetAddress.setTabSize(4);
        fieldStreetAddress.setWrapStyleWord(true);
        fieldStreetAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldStreetAddress11.setViewportView(fieldStreetAddress);

        jLabel20.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel20.setText("DOB(YYYY/MM/DD)");

        jLabel17.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel17.setText("First Name");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nw2.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel17)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldFirstName3)
                            .addComponent(fieldLastName)
                            .addComponent(fieldStreetAddress11, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel43))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldBirthday)
                            .addComponent(fieldHeight)
                            .addComponent(fieldWeight)
                            .addComponent(fieldSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldFirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(fieldBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(fieldHeight)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19)
                            .addComponent(fieldStreetAddress11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel43)
                                    .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel44)
                                    .addComponent(fieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFirstName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstName3ActionPerformed
           
    }//GEN-LAST:event_fieldFirstName3ActionPerformed

    private void fieldMRNAlergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMRNAlergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMRNAlergy1ActionPerformed

    private void fieldHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHeightActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void homeAddressZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAddressZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeAddressZipcodeActionPerformed

    private void homeAddressCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAddressCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeAddressCityActionPerformed

    private void addressZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressZipCodeActionPerformed

    private void homeAddressSL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAddressSL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeAddressSL1ActionPerformed

    private void addressCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressCityActionPerformed

    private void localAddressZC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localAddressZC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localAddressZC3ActionPerformed

    private void localAddressCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localAddressCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localAddressCityActionPerformed

    private void addressStreetLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressStreetLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressStreetLine1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressCity;
    private javax.swing.JTextField addressCountry;
    private javax.swing.JTextField addressState;
    private javax.swing.JTextField addressStreetLine1;
    private javax.swing.JTextField addressStreetLine2;
    private javax.swing.JTextField addressZipCode;
    private javax.swing.JTextField fieldAccountBalance;
    private javax.swing.JTextField fieldAccountBalance1;
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldAccountType1;
    private javax.swing.JTextField fieldBAN;
    private javax.swing.JTextField fieldBAN1;
    private javax.swing.JTextField fieldBRN;
    private javax.swing.JTextField fieldBRN1;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldBankName1;
    private javax.swing.JTextField fieldBirthday;
    private javax.swing.JTextField fieldBloodType;
    private javax.swing.JTextField fieldDOE;
    private javax.swing.JTextField fieldDateIssued;
    private javax.swing.JTextField fieldFirstName3;
    private javax.swing.JTextField fieldHeight;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldLicenceNumber;
    private javax.swing.JTextField fieldMRNAlergy1;
    private javax.swing.JTextField fieldMRNAlergy2;
    private javax.swing.JTextField fieldMRNAlergy3;
    private javax.swing.JTextField fieldSSN;
    private javax.swing.JTextArea fieldStreetAddress;
    private javax.swing.JScrollPane fieldStreetAddress11;
    private javax.swing.JTextField fieldWeight;
    private javax.swing.JTextField homeAddressCity;
    private javax.swing.JTextField homeAddressCountry;
    private javax.swing.JTextField homeAddressL2;
    private javax.swing.JTextField homeAddressSL1;
    private javax.swing.JTextField homeAddressState;
    private javax.swing.JTextField homeAddressZipcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JTextField localAddressCity;
    private javax.swing.JTextField localAddressCountry;
    private javax.swing.JTextField localAddressSL1;
    private javax.swing.JTextField localAddressSL2;
    private javax.swing.JTextField localAddressState;
    private javax.swing.JTextField localAddressZC3;
    private javax.swing.JLabel photoLicence;
    private javax.swing.JTabbedPane tab4;
    private javax.swing.JPanel tabAccount;
    private javax.swing.JPanel tabAddress3;
    private javax.swing.JPanel tabLicence;
    private javax.swing.JPanel tabMedical;
    // End of variables declaration//GEN-END:variables
}
