/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Domain.Account;
import Domain.Adress;
import Domain.DriversLicence;
import Domain.MedicalRecord;
import Domain.Person;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javafx.stage.FileChooser;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 主子
 */
public class PersonCreate extends javax.swing.JPanel {

    /**
     * Creates new form PersonCreate
     */
    Person person;
    JFileChooser chooser;
    ImageIcon imgThisImg;
    List<Person> personsInfo;
    public PersonCreate(Person person) {
        initComponents();
        this.person=person;
        this.fieldAccountBalance.setText(""+0);
        this.fieldAccountBalance1.setText("" + 0);
        personsInfo=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        fieldFirstName3 = new javax.swing.JTextField();
        fieldWeight = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        tab4 = new javax.swing.JTabbedPane();
        tabAddress3 = new javax.swing.JPanel();
        localAddressZC3 = new javax.swing.JTextField();
        localAddressCountry = new javax.swing.JTextField();
        homeAddressState = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        homeAddressSL1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        homeAddressL2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        homeAddressCity = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        homeAddressZipcode = new javax.swing.JTextField();
        homeAddressCountry = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        addressStreetLine1 = new javax.swing.JTextField();
        addressStreetLine2 = new javax.swing.JTextField();
        addressCity = new javax.swing.JTextField();
        addressState = new javax.swing.JTextField();
        addressZipCode = new javax.swing.JTextField();
        addressCountry = new javax.swing.JTextField();
        localAddressState = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        localAddressSL1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        localAddressSL2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        localAddressCity = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tabAccount = new javax.swing.JPanel();
        fieldBankName1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        fieldBRN1 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        fieldBAN1 = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldAccountBalance1 = new javax.swing.JTextField();
        fieldBRN = new javax.swing.JTextField();
        fieldAccountType1 = new javax.swing.JTextField();
        fieldBAN = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        fieldAccountBalance = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        fieldAccountType = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        tabLicence = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        fieldLicenceNumber = new javax.swing.JTextField();
        fieldDOE = new javax.swing.JTextField();
        fieldBloodType = new javax.swing.JTextField();
        fieldDateIssued = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        photoLicence = new javax.swing.JLabel();
        tabMedical = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        fieldMRNAlergy1 = new javax.swing.JTextField();
        fieldMRNAlergy2 = new javax.swing.JTextField();
        fieldMRNAlergy3 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fieldSSN = new javax.swing.JTextField();
        fieldBirthday = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        fieldHeight = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldStreetAddress11 = new javax.swing.JScrollPane();
        areaStreetAddress = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(62, 188, 202));
        setMinimumSize(new java.awt.Dimension(852, 549));

        jLabel27.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Height");

        fieldFirstName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstName3ActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel44.setText("SSN");

        tab4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tab4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab4.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        tabAddress3.setBackground(new java.awt.Color(62, 188, 202));
        tabAddress3.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        tabAddress3.setPreferredSize(new java.awt.Dimension(827, 585));

        localAddressZC3.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        localAddressZC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localAddressZC3ActionPerformed(evt);
            }
        });

        localAddressCountry.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        homeAddressState.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel21.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel21.setText("Street Line1");

        jLabel22.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel22.setText("Street Line2");

        homeAddressSL1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        homeAddressSL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAddressSL1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel23.setText("City");

        homeAddressL2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel24.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel24.setText("State");

        homeAddressCity.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        homeAddressCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAddressCityActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel25.setText("Zip code");

        jLabel26.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel26.setText("Country");

        homeAddressZipcode.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        homeAddressZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAddressZipcodeActionPerformed(evt);
            }
        });

        homeAddressCountry.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel28.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel28.setText("Work Address");

        jLabel29.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel29.setText("Local Address");

        jLabel30.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel30.setText("Home Address");

        jLabel31.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel31.setText("Street Line1");

        jLabel32.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel32.setText("Street Line2");

        jLabel33.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel33.setText("City");

        jLabel34.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel34.setText("State");

        jLabel35.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel35.setText("Zip code");

        jLabel36.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel36.setText("Country");

        addressStreetLine1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        addressStreetLine2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        addressCity.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        addressCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressCityActionPerformed(evt);
            }
        });

        addressState.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        addressZipCode.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        addressZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressZipCodeActionPerformed(evt);
            }
        });

        addressCountry.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        localAddressState.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel37.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel37.setText("Street Line1");

        jLabel38.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel38.setText("Street Line2");

        localAddressSL1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel39.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel39.setText("City");

        localAddressSL2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel40.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel40.setText("State");

        localAddressCity.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        localAddressCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localAddressCityActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel41.setText("Zip code");

        jLabel42.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel42.setText("Country");

        javax.swing.GroupLayout tabAddress3Layout = new javax.swing.GroupLayout(tabAddress3);
        tabAddress3.setLayout(tabAddress3Layout);
        tabAddress3Layout.setHorizontalGroup(
            tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddress3Layout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddress3Layout.createSequentialGroup()
                        .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homeAddressL2)
                            .addComponent(homeAddressCity)
                            .addComponent(homeAddressZipcode)
                            .addComponent(homeAddressCountry)
                            .addComponent(homeAddressSL1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(homeAddressState)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddress3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(69, 69, 69)))
                .addContainerGap())
            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabAddress3Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabAddress3Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(jLabel31)
                                .addComponent(jLabel33)
                                .addComponent(jLabel34)
                                .addComponent(jLabel35)
                                .addComponent(jLabel36))
                            .addGap(3, 3, 3)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressStreetLine2)
                                .addComponent(addressCity)
                                .addComponent(addressZipCode)
                                .addComponent(addressCountry)
                                .addComponent(addressState)
                                .addComponent(addressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tabAddress3Layout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(196, 196, 196)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29)
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel38)
                                        .addComponent(jLabel37)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel40)
                                        .addComponent(jLabel41)
                                        .addComponent(jLabel42))
                                    .addGap(3, 3, 3)
                                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(localAddressZC3)
                                        .addComponent(localAddressCountry)
                                        .addComponent(localAddressSL2)
                                        .addComponent(localAddressCity)
                                        .addGroup(tabAddress3Layout.createSequentialGroup()
                                            .addComponent(localAddressSL1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(localAddressState))))))
                    .addGap(276, 276, 276)))
        );
        tabAddress3Layout.setVerticalGroup(
            tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddress3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(28, 28, 28)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(homeAddressSL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(homeAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAddress3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel24))
                    .addGroup(tabAddress3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(homeAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(homeAddressZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(homeAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabAddress3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29))
                    .addGap(28, 28, 28)
                    .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabAddress3Layout.createSequentialGroup()
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(addressStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(addressStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33)
                                .addComponent(addressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel34))
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(addressState, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(addressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel36)
                                .addComponent(addressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tabAddress3Layout.createSequentialGroup()
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel37)
                                .addComponent(localAddressSL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel38)
                                .addComponent(localAddressSL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel39)
                                .addComponent(localAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel40))
                                .addGroup(tabAddress3Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(localAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel41)
                                .addComponent(localAddressZC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(tabAddress3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel42)
                                .addComponent(localAddressCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tab4.addTab("Address", tabAddress3);

        tabAccount.setBackground(new java.awt.Color(62, 188, 202));

        fieldBankName1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel1.setText("Checking Account");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel2.setText("Saving Account");

        jLabel45.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel45.setText("Bank Name");

        jLabel46.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel46.setText("Bank Routing Number");

        jLabel47.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel47.setText("Bank Account Number");

        jLabel48.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel48.setText("Account Balance");

        fieldBRN1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel49.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel49.setText("Account Type");

        fieldBAN1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBankName.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldAccountBalance1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBRN.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldAccountType1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBAN.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel61.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel61.setText("Bank Name");

        fieldAccountBalance.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel62.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel62.setText("Bank Routing Number");

        fieldAccountType.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel63.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel63.setText("Bank Account Number");

        jLabel64.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel64.setText("Account Balance");

        jLabel65.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel65.setText("Account Type");

        javax.swing.GroupLayout tabAccountLayout = new javax.swing.GroupLayout(tabAccount);
        tabAccount.setLayout(tabAccountLayout);
        tabAccountLayout.setHorizontalGroup(
            tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(tabAccountLayout.createSequentialGroup()
                            .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel48)
                                .addComponent(jLabel49))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldBRN, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tabAccountLayout.createSequentialGroup()
                            .addComponent(jLabel45)
                            .addGap(121, 121, 121)
                            .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63)
                    .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(tabAccountLayout.createSequentialGroup()
                            .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel64)
                                .addComponent(jLabel65))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldAccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldAccountBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldBAN1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldBRN1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tabAccountLayout.createSequentialGroup()
                            .addComponent(jLabel61)
                            .addGap(121, 121, 121)
                            .addComponent(fieldBankName1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        tabAccountLayout.setVerticalGroup(
            tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabAccountLayout.createSequentialGroup()
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBankName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBRN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBAN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAccountBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel64))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel65)
                            .addComponent(fieldAccountType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabAccountLayout.createSequentialGroup()
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBankName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBRN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(fieldAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(362, Short.MAX_VALUE))
        );

        tab4.addTab("Account", tabAccount);

        tabLicence.setBackground(new java.awt.Color(62, 188, 202));
        tabLicence.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel50.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel50.setText("License Number");

        jLabel51.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel51.setText("Date of Expiration");

        jLabel52.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel52.setText("Blood Type");

        jLabel53.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel53.setText("Date issued");

        jLabel54.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel54.setText("DRIVING LICENSE");

        fieldLicenceNumber.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldDOE.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldBloodType.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldDateIssued.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jButton1.setText("Add Your Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        photoLicence.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        photoLicence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLicence.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout tabLicenceLayout = new javax.swing.GroupLayout(tabLicence);
        tabLicence.setLayout(tabLicenceLayout);
        tabLicenceLayout.setHorizontalGroup(
            tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLicenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(photoLicence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabLicenceLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldDateIssued, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldLicenceNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(fieldDOE))))
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        tabLicenceLayout.setVerticalGroup(
            tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLicenceLayout.createSequentialGroup()
                .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabLicenceLayout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(fieldLicenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(fieldDOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(fieldBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(fieldDateIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabLicenceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(photoLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        tab4.addTab("Driver's License", tabLicence);

        tabMedical.setBackground(new java.awt.Color(62, 188, 202));
        tabMedical.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel55.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel55.setText("Alergy1");

        jLabel56.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel56.setText("Alergy2");

        jLabel57.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel57.setText("Alergy3");

        fieldMRNAlergy1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        fieldMRNAlergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMRNAlergy1ActionPerformed(evt);
            }
        });

        fieldMRNAlergy2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        fieldMRNAlergy3.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel58.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel58.setText("MRN");

        jLabel59.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel59.setText("MRN");

        jLabel60.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel60.setText("MRN");

        javax.swing.GroupLayout tabMedicalLayout = new javax.swing.GroupLayout(tabMedical);
        tabMedical.setLayout(tabMedicalLayout);
        tabMedicalLayout.setHorizontalGroup(
            tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMedicalLayout.createSequentialGroup()
                .addGroup(tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabMedicalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(tabMedicalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldMRNAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabMedicalLayout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                        .addComponent(jLabel57)
                        .addGap(114, 114, 114))
                    .addGroup(tabMedicalLayout.createSequentialGroup()
                        .addComponent(fieldMRNAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldMRNAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        tabMedicalLayout.setVerticalGroup(
            tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMedicalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldMRNAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMRNAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMRNAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(503, Short.MAX_VALUE))
        );

        tab4.addTab("Medical Record", tabMedical);

        jLabel18.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel18.setText("Last Name");

        jLabel16.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel16.setText("Person Profile Create");

        jLabel19.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel19.setText("Street Address");

        jLabel43.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel43.setText("Weight");

        fieldHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHeightActionPerformed(evt);
            }
        });

        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        areaStreetAddress.setColumns(20);
        areaStreetAddress.setLineWrap(true);
        areaStreetAddress.setRows(5);
        areaStreetAddress.setTabSize(4);
        areaStreetAddress.setWrapStyleWord(true);
        areaStreetAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fieldStreetAddress11.setViewportView(areaStreetAddress);

        jLabel20.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel20.setText("DOB(YYYY/MM/DD)");

        jLabel17.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel17.setText("First Name");

        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExit(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nw2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel17)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldFirstName3)
                            .addComponent(fieldLastName)
                            .addComponent(fieldStreetAddress11, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel43))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldBirthday)
                            .addComponent(fieldHeight)
                            .addComponent(fieldWeight)
                            .addComponent(fieldSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldFirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(fieldBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(fieldHeight)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(fieldStreetAddress11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel43)
                                    .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel44)
                                    .addComponent(fieldSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)))
                .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFirstName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstName3ActionPerformed

    }//GEN-LAST:event_fieldFirstName3ActionPerformed

    private void localAddressZC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localAddressZC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localAddressZC3ActionPerformed

    private void homeAddressSL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAddressSL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeAddressSL1ActionPerformed

    private void homeAddressCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAddressCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeAddressCityActionPerformed

    private void homeAddressZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAddressZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeAddressZipcodeActionPerformed

    private void addressCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressCityActionPerformed

    private void addressZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressZipCodeActionPerformed

    private void localAddressCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localAddressCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localAddressCityActionPerformed

    private void fieldMRNAlergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMRNAlergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMRNAlergy1ActionPerformed

    private void fieldHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHeightActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        int result=chooser.showSaveDialog(null);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF &PGC &PAD files", "jpg", "gif", "pgc", "pad");
        chooser.setFileFilter(filter);
        String fileName = chooser.getSelectedFile().getPath();
        imgThisImg = new ImageIcon(new ImageIcon(fileName)
                .getImage().getScaledInstance(this.photoLicence.getWidth(), this.photoLicence.getHeight(), Image.SCALE_DEFAULT));
        this.photoLicence.setIcon(imgThisImg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        person.setFirstName(fieldFirstName3.getText());
        person.setLastName(this.fieldLastName.getText());
        person.setDateOfBirth(this.fieldBirthday.getText());
        person.setHeight(this.fieldHeight.getText());
        person.setSSN(this.fieldSSN.getText());
        person.setStreetAddressArea(this.areaStreetAddress.getText());
        person.setWeight(this.fieldWeight.getText());
        
        Adress address=new Adress();
        //Work Address
        String add=this.addressStreetLine1.getText();
        address.setAdressLine1(add);
        person.setWorkAdress(address);
        
        add=this.addressStreetLine2.getText();
        address.setAdressLine2(add);
        person.setWorkAdress(address);
        
        add=this.addressCountry.getText();
        address.setCountry(add);
        person.setWorkAdress(address);
        
        add=this.addressState.getText();
        address.setState(add);
        person.setWorkAdress(address);
        
        add=this.addressCity.getText();
        address.setCity(add);
        person.setWorkAdress(address);
        
        add=this.addressZipCode.getText();
        address.setZipCode(add);
        person.setWorkAdress(address);
        
        //Local Address
        address=new Adress();
        add=this.localAddressSL1.getText();
        address.setAdressLine1(add);
        
        add=this.localAddressSL2.getText();
        address.setAdressLine2(add);
        
        add=this.localAddressCountry.getText();
        address.setCountry(add);
        
        add=this.localAddressState.getText();
        address.setState(add);
        
        add=this.localAddressCity.getText();
        address.setCity(add);
        
        add=this.localAddressZC3.getText();
        address.setZipCode(add);
        person.setLocalAdress(address);
        
//Home Address
        address = new Adress();
        add=this.homeAddressSL1.getText();
        address.setAdressLine1(add);

        add=this.homeAddressL2.getText();
        address.setAdressLine2(add);

        add=this.homeAddressCountry.getText();
        address.setCountry(add);
        
        add=this.homeAddressState.getText();
        address.setState(add);
        
        add=this.homeAddressCity.getText();
        address.setCity(add);
        
        add=this.homeAddressZipcode.getText();
        address.setZipCode(add);
        person.setHomeAdress(address);

        //Saving Account
        Account account=new Account();
        add=this.fieldBankName.getText();
        account.setBankName(add);
        
        add=this.fieldBAN.getText();
        account.setBankAccountNumber(add);
        
        add=this.fieldBRN.getText();
        account.setBankRoutingNumber(add);
        
        
        add=this.fieldAccountBalance.getText();
        double dd=Double.valueOf(add);
        account.setAccountBalance(dd);
        
        add=this.fieldAccountType.getText();
        account.setAccountType(add);       
        person.setSavingAccount(account);
        
        //Checking Account
        account=new Account();
        add=this.fieldBankName1.getText();
        account.setBankName(add);
        
        add=this.fieldBAN1.getText();
        account.setBankAccountNumber(add);
        
        add=this.fieldBRN1.getText();
        account.setBankRoutingNumber(add);
        
        add=this.fieldAccountType1.getText();
        account.setAccountType(add);
        
//      
        
        add=this.fieldAccountBalance1.getText();
        double dd1= Double.valueOf(add);
        account.setAccountBalance(dd1);

        person.setCheckingAccount(account);
        
        //Driver's Licence
        DriversLicence driver=new DriversLicence();
        add=this.fieldLicenceNumber.getText();
        driver.setLicenceNumber(add);
        
        add=this.fieldDateIssued.getText();
        driver.setDateIssued(add);
        
        add=this.fieldDOE.getText();
        driver.setDateOfExpiration(add);
        
        add=this.fieldBloodType.getText();
        driver.setBloodType(add);
//        
//        driver.setChooser(chooser);
        driver.setImgPortrait(imgThisImg);
        person.setDriverLicence(driver);
        
        //Medical Record1
        MedicalRecord medical=new MedicalRecord();
        add=this.fieldMRNAlergy1.getText();
        medical.setMedicalRecordNumber(add);
        person.setMedicalRecord(medical);
        //Medical Record2
        medical= new MedicalRecord();
        add=this.fieldMRNAlergy2.getText();
        medical.setMedicalRecordNumber(add);
        person.setMedicalRecord(medical);

        //Medical Record3
        medical = new MedicalRecord();
        add = this.fieldMRNAlergy3.getText();
        medical.setMedicalRecordNumber(add);
        person.setMedicalRecord(medical);
        
        JOptionPane.showMessageDialog(this,"save completed");
        
        //save infomation of each person
        personsInfo.add(person);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        // TODO add your handling code here:
        JButton jbut=(JButton)evt.getSource();
        jbut.setForeground(Color.white);
        jbut.setBackground(Color.red);
    }//GEN-LAST:event_saveMouseEntered

    private void buttonMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExit
        // TODO add your handling code here:
        JButton jbut=(JButton)evt.getSource();
        jbut.setForeground(Color.black);
        jbut.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_buttonMouseExit


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressCity;
    private javax.swing.JTextField addressCountry;
    private javax.swing.JTextField addressState;
    private javax.swing.JTextField addressStreetLine1;
    private javax.swing.JTextField addressStreetLine2;
    private javax.swing.JTextField addressZipCode;
    private javax.swing.JTextArea areaStreetAddress;
    private javax.swing.JTextField fieldAccountBalance;
    private javax.swing.JTextField fieldAccountBalance1;
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldAccountType1;
    private javax.swing.JTextField fieldBAN;
    private javax.swing.JTextField fieldBAN1;
    private javax.swing.JTextField fieldBRN;
    private javax.swing.JTextField fieldBRN1;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldBankName1;
    private javax.swing.JTextField fieldBirthday;
    private javax.swing.JTextField fieldBloodType;
    private javax.swing.JTextField fieldDOE;
    private javax.swing.JTextField fieldDateIssued;
    private javax.swing.JTextField fieldFirstName3;
    private javax.swing.JTextField fieldHeight;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldLicenceNumber;
    private javax.swing.JTextField fieldMRNAlergy1;
    private javax.swing.JTextField fieldMRNAlergy2;
    private javax.swing.JTextField fieldMRNAlergy3;
    private javax.swing.JTextField fieldSSN;
    private javax.swing.JScrollPane fieldStreetAddress11;
    private javax.swing.JTextField fieldWeight;
    private javax.swing.JTextField homeAddressCity;
    private javax.swing.JTextField homeAddressCountry;
    private javax.swing.JTextField homeAddressL2;
    private javax.swing.JTextField homeAddressSL1;
    private javax.swing.JTextField homeAddressState;
    private javax.swing.JTextField homeAddressZipcode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JTextField localAddressCity;
    private javax.swing.JTextField localAddressCountry;
    private javax.swing.JTextField localAddressSL1;
    private javax.swing.JTextField localAddressSL2;
    private javax.swing.JTextField localAddressState;
    private javax.swing.JTextField localAddressZC3;
    private javax.swing.JLabel photoLicence;
    private javax.swing.JButton saveButton;
    private javax.swing.JTabbedPane tab4;
    private javax.swing.JPanel tabAccount;
    private javax.swing.JPanel tabAddress3;
    private javax.swing.JPanel tabLicence;
    private javax.swing.JPanel tabMedical;
    // End of variables declaration//GEN-END:variables
}
